name: carclenx_vendor_app
description: Pexa Partner App.
publish_to: 'none' #
version: 1.0.1+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^12.0.3
  path_provider: ^2.0.10
  url_strategy: ^0.2.0
  pin_code_fields: ^7.4.0
  http: ^0.13.5
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.1.0+1
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  google_maps_flutter: ^2.2.1
  url_launcher: ^6.1.2
  vibration: 1.7.4-nullsafety.0
  image_picker: ^0.8.5+3
  disable_battery_optimization: ^1.1.0+1
  phone_number: ^0.12.0+2
  country_code_picker: ^2.0.2
  location: ^4.4.0
  audioplayers: ^0.20.1
  flutter_widget_from_html_core: ^0.8.5+3
  fwfh_text_style: ^2.22.8+1 
  marquee: ^2.2.3
  pull_to_refresh_flutter3: ^2.0.1
  cached_network_image: ^3.2.2
  device_info_plus: ^8.0.0
  logger: ^1.1.0
  drop_down_list: ^0.0.4
  file_picker: ^5.2.1
  loading_animation_widget: ^1.2.0+3
  carousel_slider: ^4.1.1
  firebase_analytics: ^10.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900